name: web-rob-ci

on:
  push:
    branches: [master]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '18.17.1'

      - name: 'Install dependencies'
        run: npm install
        env:
          CI: true

      - name: 'Build'
        run: npm run build